import { Hono } from 'hono';

import { env } from '../config/env.js';
import { FEE_SPONSORED, activeNetwork, type NetworkConstants } from '../config/x402.js';
import { catalogRoutes, type CatalogRoute } from '../pricing.js';
import { gatedRoutes } from '../gate/routes.js';
import { listConnectors, registry } from '../connectors/registry.js';
import type { Connector } from '../connectors/types.js';
import type { KpiId, ProtocolClass } from '../standardize/schema.js';

/**
 * GET /catalog — API_SPEC.md §3.4. Free (API_SPEC.md §1).
 *
 * Two properties this file exists to hold:
 *
 * 1. `protocols[]` is GENERATED by iterating the connector registry and calling
 *    `capabilities()`. There is no static list to fall out of date, so it is
 *    structurally impossible to advertise a KPI no connector implements.
 * 2. Every payment value comes from `src/config/x402.ts` and the validated env,
 *    and every price from `src/pricing.ts` — the same module the step-6 payment
 *    middleware charges from. Nothing here is retyped, so the advertised price
 *    and the charged price cannot drift (ARCHITECTURE.md §4.1).
 */

export interface CatalogPayment {
  protocol: 'x402';
  version: number;
  scheme: string;
  /** ASA id as a string, matching the §2.1 payment requirement encoding. */
  asset: string;
  asset_symbol: string;
  decimals: number;
  /** CAIP-2 network id. */
  network: string;
  facilitator: string;
  payTo: string;
  fee_sponsored: boolean;
}

export interface CatalogProtocol {
  id: string;
  name: string;
  class: ProtocolClass;
  kpis: KpiId[];
  sources: string[];
  /**
   * KPIs this connector applies to its class but deliberately does NOT publish,
   * mapped to the reason `/metric` returns with its 404 `KPI_NOT_APPLICABLE`.
   *
   * Present because `kpis` alone cannot distinguish "we have not built this"
   * from "the source does not disclose it", and for the motivating case —
   * Pact's fee split — that difference is the finding. An agent reading only
   * `kpis` would see Pact missing `take_rate` and conclude our coverage is
   * thin; the reason says the gap is in Pact's disclosure, not in ours
   * (DATA_SCHEMA.md §1.5, CONNECTOR_GUIDE.md §1.5).
   *
   * Omitted entirely when a connector declines nothing, so the common case
   * carries no empty object.
   */
  declined?: Record<string, string>;
}

export interface CatalogBody {
  service: string;
  methodology_version: string;
  network: string;
  payment: CatalogPayment;
  protocols: CatalogProtocol[];
  routes: CatalogRoute[];
}

export const SERVICE_NAME = 'AlgoTerminal';

/** §3.4's `"network": "algorand-mainnet"` — the chain, not the CAIP-2 id. */
export function networkLabel(network: string): string {
  return `algorand-${network}`;
}

/**
 * The §3.4 `payment` block. Every value comes from `src/config/x402.ts` or the
 * validated env; nothing is retyped here, because a mistyped CAIP-2 id or ASA
 * id fails as a rejected settlement in production rather than a compile error.
 *
 * The network is a parameter so it can be asserted against the mainnet
 * constants without a process configured for mainnet.
 */
export function catalogPayment(net: NetworkConstants = activeNetwork()): CatalogPayment {
  return {
    protocol: 'x402',
    version: net.x402Version,
    scheme: net.scheme,
    asset: String(net.usdcAsaId),
    asset_symbol: net.usdcSymbol,
    decimals: net.usdcDecimals,
    network: net.caip2,
    facilitator: env.X402_FACILITATOR_URL,
    payTo: env.X402_PAYTO,
    fee_sponsored: FEE_SPONSORED,
  };
}

/**
 * A connector's capabilities as a `/catalog` entry.
 *
 * Copies the declared arrays rather than passing the connector's own readonly
 * ones through to `c.json`, so a connector cannot hand out a live reference to
 * its internal state.
 */
export function catalogProtocol(connector: Connector): CatalogProtocol {
  const caps = connector.capabilities();
  const declined = { ...(caps.declined ?? {}) } as Record<string, string>;
  return {
    id: caps.id,
    name: caps.name,
    class: caps.class,
    kpis: [...caps.kpis],
    // §3.4 publishes this as `sources`; on the connector it is `sourceHosts`,
    // to keep it distinct from a snapshot's per-fetch SourceRef[] (§1.1).
    sources: [...caps.sourceHosts],
    // Spread into a fresh object above for the same reason the arrays are
    // copied: a connector must not hand out a live reference to its own state.
    ...(Object.keys(declined).length > 0 ? { declined } : {}),
  };
}

/**
 * The §3.4 route table, each entry flagged with whether this deployment can
 * serve it (see {@link CatalogRoute.available}).
 *
 * Composed here rather than in `pricing.ts` because availability is the gate's
 * question, not the price table's, and `gate/routes.ts` already imports
 * `pricing.ts` — asking it the other way round would close the cycle.
 */
export function catalogRoutesWithAvailability(): CatalogRoute[] {
  const gated = new Set(gatedRoutes().map((r) => r.path));
  return catalogRoutes().map((route) => ({ ...route, available: gated.has(route.path) }));
}

export function buildCatalog(
  source: ReadonlyMap<string, Connector> = registry,
  net: NetworkConstants = activeNetwork(),
): CatalogBody {
  return {
    service: SERVICE_NAME,
    methodology_version: env.METHODOLOGY_VERSION,
    network: networkLabel(net.network),
    payment: catalogPayment(net),
    // Empty registry -> `[]`, and the route still returns valid JSON: an agent
    // discovering us mid-deploy learns we sell nothing yet, rather than getting
    // a 500 or a list of protocols we cannot serve.
    protocols: listConnectors(source).map(catalogProtocol),
    routes: catalogRoutesWithAvailability(),
  };
}

export const catalog = new Hono();

catalog.get('/catalog', (c) => c.json(buildCatalog()));
