export default function TrustedBy() {
  return (
    <>
    <div className="container-1240">
      <div className="trusted animate-fade-in-up" style={{ animationDelay: ".5s" }}>
        <div className="trusted-label">Trusted by</div>
        <div className="logo-grid"><img alt="google" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/google.svg" /><img alt="binance" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/binance.svg" /><img alt="bloomberg" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/bloomberg.svg" /><img alt="coingecko" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/coingecko.svg" /><img alt="morgan-stanley" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/morgan-stanley.svg" /><img alt="franklin-templeton" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/franklin-templeton.svg" /><img alt="vaneck" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/vaneck.svg" /><img alt="coinbase-ventures" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/coinbase-ventures.svg" /><img alt="bitwise" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/bitwise.svg" /><img alt="harvard-business" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/harvard-business.svg" /><img alt="standard-chartered" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/standard-chartered.svg" /><img alt="messari" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/messari.svg" /><img alt="nansen" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/nansen.svg" /><img alt="grayscale" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/grayscale.svg" /><img alt="pantera" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/pantera.svg" /><img alt="brevan-howard" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/brevan-howard.svg" /><img alt="dragonfly" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/dragonfly.svg" /><img alt="coindesk" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/coindesk.svg" /><img alt="ark-invest" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/ark-invest.svg" /><img alt="jeffries" loading="lazy" width="520" height="500" decoding="async" src="/assets/logos/jeffries.svg" /></div>
      </div>
    </div>
    </>
  );
}
