#!/usr/bin/env python3
"""Generate public/og-banner.png (1200x630) and public/favicon.png.

DEPLOYMENT.md §6.3: the Bazaar enrichment engine re-fetches these daily and uses
both for the directory card, which is the first thing a browsing agent operator
sees. They are committed as PNGs because that is what a crawler fetches, but
they are generated by this script rather than drawn by hand so that the prices
on the banner can be regenerated from the price table instead of being retyped
when it changes:

    python3 scripts/make-og-assets.py

Prices are passed in from `npm run og:assets`, which reads them out of
`src/pricing.ts` — the same module the payment gate charges from. Running this
file directly falls back to the literals below, which the npm script's output
will overwrite.
"""

from __future__ import annotations

import json
import os
import sys
from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
BG = (14, 16, 19)
CARD = (21, 24, 29)
LINE = (38, 43, 51)
FG = (232, 234, 238)
SUB = (154, 162, 177)
ACCENT = (90, 215, 171)

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "public")

# Overridden by `npm run og:assets`, which reads the real table from pricing.ts.
DEFAULT_PRICES = [
    ("GET /metric/{protocol}/{kpi}", "$0.005", "one KPI, one protocol"),
    ("GET /compare", "$0.05", "one KPI, 2-5 protocols"),
    ("POST /ask", "$0.15", "a question, answered from facts"),
]
DEFAULT_PROTOCOLS = ["Tinyman", "Pact", "Folks Finance"]


def font(size: int, *, bold: bool = False, mono: bool = False) -> ImageFont.FreeTypeFont:
    """A real system face, with a fallback chain that ends somewhere legible."""
    candidates = (
        ["/System/Library/Fonts/SFNSMono.ttf", "/System/Library/Fonts/Menlo.ttc"]
        if mono
        else ["/System/Library/Fonts/SFNS.ttf", "/System/Library/Fonts/Helvetica.ttc"]
    )
    for path in candidates:
        try:
            f = ImageFont.truetype(path, size)
        except OSError:
            continue
        if bold:
            # SFNS.ttf is variable; named instances are the only way to get a
            # real bold rather than a synthesised one.
            try:
                f.set_variation_by_name("Bold")
            except Exception:
                pass
        return f
    return ImageFont.load_default(size)


def rounded(draw: ImageDraw.ImageDraw, box, radius, fill=None, outline=None, width=1) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def build_banner(prices, protocols) -> Image.Image:
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)

    # A faint grid, so the card reads as an instrument panel rather than a
    # poster. Subtle enough to survive the directory's own downscaling.
    for x in range(0, W, 40):
        d.line([(x, 0), (x, H)], fill=(19, 22, 26), width=1)
    for y in range(0, H, 40):
        d.line([(0, y), (W, y)], fill=(19, 22, 26), width=1)

    pad = 72

    # Eyebrow
    d.text((pad, 64), "ALGORAND  ·  x402  ·  USDC", font=font(20, mono=True), fill=ACCENT)

    # Wordmark
    d.text((pad, 104), "AlgoTerminal", font=font(78, bold=True), fill=FG)

    # One sentence, the same one the landing page leads with.
    d.text(
        (pad, 206),
        "Standardized financial KPIs for Algorand DeFi,",
        font=font(31),
        fill=SUB,
    )
    d.text(
        (pad, 246),
        "computed under one accounting policy and priced per query.",
        font=font(31),
        fill=SUB,
    )

    # Price cards — the thing an operator is actually looking for.
    card_y, card_h, gap = 322, 132, 20
    card_w = (W - pad * 2 - gap * (len(prices) - 1)) // len(prices)
    for i, (route, price, when) in enumerate(prices):
        x = pad + i * (card_w + gap)
        rounded(d, [x, card_y, x + card_w, card_y + card_h], 12, fill=CARD, outline=LINE)
        d.text((x + 20, card_y + 18), price, font=font(38, bold=True), fill=ACCENT)
        d.text((x + 20, card_y + 68), route, font=font(15, mono=True), fill=FG)
        d.text((x + 20, card_y + 92), when, font=font(16), fill=SUB)

    # Footer rule + coverage
    d.line([(pad, 512), (W - pad, 512)], fill=LINE, width=1)
    d.text(
        (pad, 536),
        "  ·  ".join(protocols),
        font=font(23, bold=True),
        fill=FG,
    )
    d.text(
        (pad, 570),
        "TVL · fees · revenue · take rate · capital efficiency — with provenance and a confidence score",
        font=font(17),
        fill=SUB,
    )
    return img


def build_favicon() -> Image.Image:
    """A 512x512 mark: the 'A' terminal block. Downscales to 16px legibly."""
    s = 512
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    rounded(d, [0, 0, s - 1, s - 1], 112, fill=BG)
    rounded(d, [8, 8, s - 9, s - 9], 106, outline=(40, 46, 55), width=6)
    f = font(300, bold=True)
    # Center on the glyph's own ink box, not on the font's line box: an 'A'
    # centred by line metrics sits visibly high at favicon sizes.
    box = d.textbbox((0, 0), "A", font=f)
    d.text(
        ((s - (box[2] - box[0])) / 2 - box[0], (s - (box[3] - box[1])) / 2 - box[1]),
        "A",
        font=f,
        fill=ACCENT,
    )
    return img


def main() -> int:
    prices, protocols = DEFAULT_PRICES, DEFAULT_PROTOCOLS
    if not sys.stdin.isatty():
        raw = sys.stdin.read().strip()
        if raw:
            data = json.loads(raw)
            prices = [tuple(p) for p in data["prices"]]
            protocols = data["protocols"]

    os.makedirs(OUT_DIR, exist_ok=True)
    banner_path = os.path.join(OUT_DIR, "og-banner.png")
    favicon_path = os.path.join(OUT_DIR, "favicon.png")

    build_banner(prices, protocols).save(banner_path, "PNG", optimize=True)
    build_favicon().save(favicon_path, "PNG", optimize=True)

    for path in (banner_path, favicon_path):
        with Image.open(path) as im:
            print(f"{path}  {im.size[0]}x{im.size[1]}  {os.path.getsize(path)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
