/**
 * Records the live-data fixtures for the Tinyman connector
 * (CONNECTOR_GUIDE.md §Step 6).
 *
 *   npx tsx --env-file=.env scripts/record-tinyman-fixtures.ts
 *
 * `pools-page-{1,2}.json` (the V1.1 list) stay as recorded with curl at step 4
 * and are not touched here. Everything else this script writes came off the
 * live API on the day it ran:
 *
 *   v2-accounts.json    verbatim indexer account records for a chosen subset of
 *                       V2 pools, assembled into two pages. The account objects
 *                       are byte-for-byte what the indexer returned; only the
 *                       page ENVELOPE (`next-token`) is synthesised, so the
 *                       fixture exercises a real multi-page walk without
 *                       carrying 31MB of it.
 *   assets.json         verbatim /assets/?ids= records — decimals for the
 *                       reserve conversion.
 *   v2-flows.json       verbatim /pools/{address}/ records for the pools that
 *                       clear the §3.6 floor — the 24h flows.
 *   prices.json         a real PriceTable, resolved through the §3.7 ladder.
 *   active-users.json   a real §4.1 indexer scan over a deliberately NARROW
 *                       round window (a full 24h scan of both validator apps
 *                       moves ~250MB, see the connector README).
 *
 * The subset is chosen to be REPRESENTATIVE rather than convenient: the pools
 * that dominate TVL, plus dust pools, plus empty pools, plus pools whose assets
 * the §3.7 ladder cannot price. A fixture holding only healthy pools would let
 * every exclusion path rot untested.
 *
 * `expected-facts.json`, the golden file, is written by the test suite's
 * `UPDATE_GOLDEN=1` path rather than here, so the golden can only ever be
 * regenerated by the same code the assertion runs against.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';

import { pino } from 'pino';

import { createHttpClient } from '../src/connectors/http.js';
import { createAlgodClient } from '../src/connectors/algod.js';
import { createIndexerClient } from '../src/connectors/indexer.js';
import { createPriceService } from '../src/connectors/price/index.js';
import { assetsUrl, poolByAddressUrl } from '../src/connectors/tinyman/enumerate.js';
import { V1_VALIDATOR_APP_ID, V2_VALIDATOR_APP_ID } from '../src/connectors/tinyman/index.js';
import { MIN_TVL_USD } from '../src/standardize/types.js';
import { loadRecordedPools } from '../test/fixtures/tinyman/recorded.js';

const FIXTURES = path.resolve('test/fixtures/tinyman');
const ALGOD = process.env.MAINNET_ALGOD_URL ?? 'https://mainnet-api.4160.nodely.dev';
const INDEXER = process.env.MAINNET_INDEXER_URL ?? 'https://mainnet-idx.4160.nodely.dev';
/** A narrow window: enough transactions to be real, small enough to record. */
const SCAN_ROUNDS = 2_000;
/** Pools per recorded indexer page — small, and >1 page, so paging is exercised. */
const PAGE_SIZE = 60;
/** The biggest pools by TVL, which is where a coverage bug would actually hurt. */
const TOP_POOLS = 45;
/** A deterministic spread of everything else: dust, empty, unpriceable. */
const SAMPLE_POOLS = 75;

const log = pino({ level: 'info' });
const http = createHttpClient({ log });

interface RawAccount {
  address: string;
  'apps-local-state'?: Array<{ id: number; 'key-value'?: Array<{ key: string; value: { type: number; bytes?: string; uint?: number } }> }>;
}

const decode = (s: string): string => Buffer.from(s, 'base64').toString('utf8');

function stateOf(account: RawAccount): Record<string, number> {
  const local = account['apps-local-state']?.find((s) => s.id === V2_VALIDATOR_APP_ID);
  const out: Record<string, number> = {};
  for (const kv of local?.['key-value'] ?? []) {
    if (kv.value.type === 2) out[decode(kv.key)] = kv.value.uint ?? 0;
  }
  return out;
}

async function main(): Promise<void> {
  const indexer = createIndexerClient({ baseUrl: INDEXER, http });
  const algod = createAlgodClient({ baseUrl: ALGOD, http });

  // ---- 1. The full walk, so the subset is chosen from reality -------------
  log.info('walking every account opted into the V2 validator app');
  const walk = await indexer.listAccountsByApplication(V2_VALIDATOR_APP_ID);
  log.info(
    { accounts: walk.accounts.length, pages: walk.pages, skipped: walk.skipped },
    'enumerated',
  );

  const uint = (a: (typeof walk.accounts)[number], k: string): number => {
    const v = a.state[k];
    return v?.type === 'uint' ? v.uint : 0;
  };
  const live = walk.accounts.filter(
    (a) => uint(a, 'asset_1_reserves') > 0 && uint(a, 'asset_2_reserves') > 0,
  );

  // ---- 2. Price everything live, to rank pools by real TVL ----------------
  const assetIds = [
    ...new Set(live.flatMap((a) => [uint(a, 'asset_1_id'), uint(a, 'asset_2_id')])),
  ];
  const decimals = await fetchDecimals(assetIds);
  const prices = createPriceService({ http, log, now: () => new Date() });
  const liveTable = await prices.resolve(assetIds);

  const valued = live.map((a) => {
    const [a1, a2] = [uint(a, 'asset_1_id'), uint(a, 'asset_2_id')];
    const [d1, d2] = [decimals.get(a1), decimals.get(a2)];
    const [p1, p2] = [liveTable.prices[a1], liveTable.prices[a2]];
    const tvl =
      d1 === undefined || d2 === undefined || p1 === undefined || p2 === undefined
        ? 0
        : (uint(a, 'asset_1_reserves') / 10 ** d1) * p1.usd +
          (uint(a, 'asset_2_reserves') / 10 ** d2) * p2.usd;
    return { address: a.address, tvl };
  });
  valued.sort((x, y) => y.tvl - x.tvl);

  // Deterministic sampling: every Nth of the remainder, plus empty pools.
  const top = valued.slice(0, TOP_POOLS).map((v) => v.address);
  const rest = valued.slice(TOP_POOLS);
  const stride = Math.max(1, Math.floor(rest.length / (SAMPLE_POOLS - 10)));
  const sampled = rest.filter((_, i) => i % stride === 0).slice(0, SAMPLE_POOLS - 10);
  const empty = walk.accounts
    .filter((a) => uint(a, 'asset_1_reserves') === 0)
    .slice(0, 10)
    .map((a) => a.address);
  const chosen = [...new Set([...top, ...sampled.map((v) => v.address), ...empty])];
  log.info({ chosen: chosen.length }, 'chosen subset');

  // ---- 3. Verbatim account records ---------------------------------------
  const accounts = (
    await Promise.all(
      chosen.map(async (address) => {
        const raw = (await http
          .getJson(`${INDEXER}/v2/accounts/${address}?exclude=assets,created-assets,created-apps`)
          .catch(() => null)) as { account?: RawAccount } | null;
        return raw?.account ?? null;
      }),
    )
  ).filter((a): a is RawAccount => a !== null);

  const pages: unknown[] = [];
  for (let i = 0; i < accounts.length; i += PAGE_SIZE) {
    const slice = accounts.slice(i, i + PAGE_SIZE);
    const isLast = i + PAGE_SIZE >= accounts.length;
    pages.push({
      accounts: slice,
      'current-round': walk.currentRound,
      ...(isLast ? {} : { 'next-token': String(pages.length + 1) }),
    });
  }
  writeFileSync(path.join(FIXTURES, 'v2-accounts.json'), `${JSON.stringify({ pages }, null, 1)}\n`);
  log.info({ accounts: accounts.length, pages: pages.length }, 'wrote v2-accounts.json');

  // ---- 4. Verbatim asset metadata for exactly those pools ----------------
  const subsetAssets = [
    ...new Set([
      ...accounts.flatMap((a) => {
        const st = stateOf(a);
        return [st['asset_1_id'] ?? 0, st['asset_2_id'] ?? 0];
      }),
      ...loadRecordedPools().flatMap((p) => [Number(p.asset_1.id), Number(p.asset_2.id)]),
    ]),
  ].sort((a, b) => a - b);

  // Keyed by asset id, not by request URL: the connector chunks whichever ids
  // it does not already know from a V1.1 record, so recording today's chunk
  // boundaries would bake a request shape into the fixture as if it were data.
  const assetRecords: Record<string, unknown> = {};
  await Promise.all(
    chunk(subsetAssets, 50).map(async (ids) => {
      const page = (await http.getJson(assetsUrl(ids)).catch(() => null)) as {
        results?: Array<{ id: string }>;
      } | null;
      for (const record of page?.results ?? []) assetRecords[record.id] = record;
    }),
  );
  writeFileSync(path.join(FIXTURES, 'assets.json'), `${JSON.stringify(assetRecords, null, 1)}\n`);
  log.info({ assets: Object.keys(assetRecords).length }, 'wrote assets.json');

  // ---- 5. Verbatim flow records for the pools that clear §3.6 ------------
  const table = await prices.resolve(subsetAssets);
  const candidates = accounts.filter((a) => {
    const st = stateOf(a);
    const [d1, d2] = [decimals.get(st['asset_1_id'] ?? -1), decimals.get(st['asset_2_id'] ?? -1)];
    const [p1, p2] = [table.prices[st['asset_1_id'] ?? -1], table.prices[st['asset_2_id'] ?? -1]];
    if (d1 === undefined || d2 === undefined || p1 === undefined || p2 === undefined) return false;
    const tvl =
      ((st['asset_1_reserves'] ?? 0) / 10 ** d1) * p1.usd +
      ((st['asset_2_reserves'] ?? 0) / 10 ** d2) * p2.usd;
    return tvl >= MIN_TVL_USD;
  });

  const flows: Record<string, unknown> = {};
  await Promise.all(
    candidates.map(async (a) => {
      const record = await http.getJson(poolByAddressUrl(a.address)).catch(() => null);
      if (record !== null) flows[a.address] = record;
    }),
  );
  writeFileSync(path.join(FIXTURES, 'v2-flows.json'), `${JSON.stringify(flows, null, 1)}\n`);
  log.info({ pools: Object.keys(flows).length }, 'wrote v2-flows.json');

  // ---- 6. Prices, through the real ladder --------------------------------
  writeFileSync(path.join(FIXTURES, 'prices.json'), `${JSON.stringify(table, null, 1)}\n`);
  log.info(
    { priced: Object.keys(table.prices).length, of: subsetAssets.length },
    'wrote prices.json',
  );

  // ---- 7. The §4.1 indexer scan ------------------------------------------
  const { lastRound } = await algod.status();
  const maxRound = lastRound;
  const minRound = maxRound - SCAN_ROUNDS;

  // Recorded as pages of `{ sender, confirmed-round }` — the only two fields
  // the §4.1 scan reads. A verbatim recording of the full transactions would be
  // ~10KB each and tens of megabytes for the window, which is a fixture nobody
  // would ever open; this is the same data projected onto what we consume.
  const scan: Record<string, Array<Array<{ sender: string; 'confirmed-round': number }>>> = {};
  for (const applicationId of [V1_VALIDATOR_APP_ID, V2_VALIDATOR_APP_ID]) {
    const collected: Array<Array<{ sender: string; 'confirmed-round': number }>> = [];
    let next: string | undefined;
    for (;;) {
      const page = await indexer.searchTransactions({
        applicationId,
        minRound,
        maxRound,
        limit: 1_000,
        ...(next === undefined ? {} : { next }),
      });
      collected.push(
        page.transactions.map((txn) => {
          const t = txn as { sender: string; 'confirmed-round': number };
          return { sender: t.sender, 'confirmed-round': t['confirmed-round'] };
        }),
      );
      if (page.nextToken === undefined) break;
      next = page.nextToken;
    }
    scan[String(applicationId)] = collected;
  }

  writeFileSync(
    path.join(FIXTURES, 'active-users.json'),
    `${JSON.stringify({ requested: { minRound, maxRound }, pages: scan }, null, 1)}\n`,
  );
  log.info({ transactions: Object.values(scan).flat(2).length }, 'wrote active-users.json');
}

function chunk<T>(items: readonly T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push([...items.slice(i, i + size)]);
  return out;
}

async function fetchDecimals(ids: readonly number[]): Promise<Map<number, number>> {
  const decimals = new Map<number, number>();
  await Promise.all(
    chunk(ids, 50).map(async (c) => {
      const page = (await http.getJson(assetsUrl(c)).catch(() => null)) as {
        results?: Array<{ id: string; decimals: number }>;
      } | null;
      for (const a of page?.results ?? []) decimals.set(Number(a.id), a.decimals);
    }),
  );
  return decimals;
}

await main();
